title: Huan Chang's Homepage
page-top-title: Huan Chang
top-section-bg-text: Be what you wanna be
home-subtitle: Huan Chang&ensp;|&ensp;常欢
copyright-text: '&copy; Huan Chang 2023-2025. All Rights Reserved.'
